// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // Answers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class Answer
    {
        public int AnswerId { get; set; } // AnswerId (Primary key)
        public int ApplicationId { get; set; } // ApplicationId
        public int QuestionId { get; set; } // QuestionId
        public int OptionId { get; set; } // OptionId

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Answer pointed by [Answers].[AnswerId] (FK_Answers_Answers)
        /// </summary>
        public virtual Answer Answer2 { get; set; } // Answers.FK_Answers_Answers

        // Foreign keys

        /// <summary>
        /// Parent Answer pointed by [Answers].([AnswerId]) (FK_Answers_Answers)
        /// </summary>
        public virtual Answer Answer1 { get; set; } // FK_Answers_Answers

        /// <summary>
        /// Parent Application pointed by [Answers].([ApplicationId]) (FK_Answers_Application)
        /// </summary>
        public virtual Application Application { get; set; } // FK_Answers_Application

        /// <summary>
        /// Parent Question pointed by [Answers].([QuestionId]) (FK_Answers_Question)
        /// </summary>
        public virtual Question Question { get; set; } // FK_Answers_Question

        public Answer()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
