// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // Message
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class Message
    {
        public int MessageId { get; set; } // MessageId (Primary key)
        public int UserIdFrom { get; set; } // UserIdFrom
        public int UserIdTo { get; set; } // UserIdTo
        public string MessageSubject { get; set; } // MessageSubject
        public string MessageBody { get; set; } // MessageBody
        public System.DateTime? DateTimeSent { get; set; } // DateTimeSent

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Message].([UserIdFrom]) (FK_dbo.Messages_dbo.User_UserIdFrom)
        /// </summary>
        public virtual User User_UserIdFrom { get; set; } // FK_dbo.Messages_dbo.User_UserIdFrom

        /// <summary>
        /// Parent User pointed by [Message].([UserIdTo]) (FK_dbo.Messages_dbo.User_UserIdTo)
        /// </summary>
        public virtual User User_UserIdTo { get; set; } // FK_dbo.Messages_dbo.User_UserIdTo

        public Message()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
