// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // Messages
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class MessageConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Message>
    {
        public MessageConfiguration()
            : this("dbo")
        {
        }

        public MessageConfiguration(string schema)
        {
            ToTable("Messages", schema);
            HasKey(x => x.MessageId);

            Property(x => x.MessageId).HasColumnName(@"MessageId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserIdFrom).HasColumnName(@"UserIdFrom").HasColumnType("int").IsRequired();
            Property(x => x.UserIdTo).HasColumnName(@"UserIdTo").HasColumnType("int").IsRequired();
            Property(x => x.MessageSubject).HasColumnName(@"MessageSubject").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.MessageBody).HasColumnName(@"MessageBody").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DateTimeSent).HasColumnName(@"DateTimeSent").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.User_UserIdFrom).WithMany(b => b.Messages_UserIdFrom).HasForeignKey(c => c.UserIdFrom).WillCascadeOnDelete(false); // FK_MessagesFrom_User
            HasRequired(a => a.User_UserIdTo).WithMany(b => b.Messages_UserIdTo).HasForeignKey(c => c.UserIdTo).WillCascadeOnDelete(false); // FK_MessagesTo_User
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
