// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // Note
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class NoteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Note>
    {
        public NoteConfiguration()
            : this("dbo")
        {
        }

        public NoteConfiguration(string schema)
        {
            ToTable("Note", schema);
            HasKey(x => x.NoteId);

            Property(x => x.NoteId).HasColumnName(@"NoteId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ApplicationId).HasColumnName(@"ApplicationId").HasColumnType("int").IsRequired();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Note_).HasColumnName(@"Note").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Application).WithMany(b => b.Notes).HasForeignKey(c => c.ApplicationId).WillCascadeOnDelete(false); // FK_Note_Application
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
