// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // Position
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class Position
    {
        public int PositionId { get; set; } // PositionId (Primary key)
        public string PositionName { get; set; } // PositionName (length: 100)
        public string PositionDescription { get; set; } // PositionDescription

        // Reverse navigation

        /// <summary>
        /// Child Applications where [Application].[PositionId] point to this entity (FK_dbo.Application_dbo.Position_PositionId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Application> Applications { get; set; } // Application.FK_dbo.Application_dbo.Position_PositionId

        public Position()
        {
            Applications = new System.Collections.Generic.List<Application>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
