// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // Question
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class Question
    {
        public int QuestionId { get; set; } // QuestionId (Primary key)
        public int QuestionTypeId { get; set; } // QuestionTypeId
        public string Question_ { get; set; } // Question

        // Reverse navigation

        /// <summary>
        /// Child Answers where [Answers].[QuestionId] point to this entity (FK_dbo.Answers_dbo.Question_QuestionId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Answer> Answers { get; set; } // Answers.FK_dbo.Answers_dbo.Question_QuestionId
        /// <summary>
        /// Child QuestionOptions where [QuestionOptions].[QuestionId] point to this entity (FK_dbo.QuestionOptions_dbo.Question_QuestionId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<QuestionOption> QuestionOptions { get; set; } // QuestionOptions.FK_dbo.QuestionOptions_dbo.Question_QuestionId

        // Foreign keys

        /// <summary>
        /// Parent QuestionType pointed by [Question].([QuestionTypeId]) (FK_dbo.Question_dbo.QuestionTypes_QuestionId)
        /// </summary>
        public virtual QuestionType QuestionType { get; set; } // FK_dbo.Question_dbo.QuestionTypes_QuestionId

        public Question()
        {
            Answers = new System.Collections.Generic.List<Answer>();
            QuestionOptions = new System.Collections.Generic.List<QuestionOption>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
