// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // QuestionType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class QuestionType
    {
        public int QuestionTypeId { get; set; } // QuestionTypeId (Primary key)
        public string QuestionType_ { get; set; } // QuestionType (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child Questions where [Question].[QuestionTypeId] point to this entity (FK_dbo.Question_dbo.QuestionTypes_QuestionTypeId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Question> Questions { get; set; } // Question.FK_dbo.Question_dbo.QuestionTypes_QuestionTypeId

        public QuestionType()
        {
            Questions = new System.Collections.Generic.List<Question>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
