// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace InternPortal.Data.Models
{

    // UserUpload
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class UserUpload
    {
        public int UploadId { get; set; } // UploadId (Primary key)
        public int? UserId { get; set; } // UserId
        public int? ApplicationId { get; set; } // ApplicationId
        public string UploadLocation { get; set; } // UploadLocation
        public string UploadTitle { get; set; } // UploadTitle
        public string UploadDescription { get; set; } // UploadDescription

        // Foreign keys

        /// <summary>
        /// Parent Application pointed by [UserUpload].([ApplicationId]) (FK_dbo.UserUploads_dbo.Application_ApplicationId)
        /// </summary>
        public virtual Application Application { get; set; } // FK_dbo.UserUploads_dbo.Application_ApplicationId

        /// <summary>
        /// Parent User pointed by [UserUpload].([UserId]) (FK_dbo.UserUploads_dbo.User_UserId)
        /// </summary>
        public virtual User User { get; set; } // FK_dbo.UserUploads_dbo.User_UserId

        public UserUpload()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
